hxlBites._chartBites = [
{
'id':'chart0001',
'type':'chart',
'subType':'row',
'ingredients':[{'name':'what','tags':['#activity','#sector']}],
'criteria':['what > 4', 'what < 11'],
'variables': ['what', 'count()'],
'chart':'',
'priority': 8,
},
{
'id':'chart0002',
'type':'chart',
'subType':'pie',
'ingredients':[{'name':'what','tags':['#activity','#sector']}],
'criteria':['what < 5', 'what > 1'],
'variables': ['what', 'count()'],
'chart':'',
'priority': 8,
},
{
'id':'chart0003',
'type':'chart',
'subType':'pie',
'ingredients':[{'name':'who','tags':['#org']}],
'criteria':['who < 5', 'who > 1'],
'variables': ['who', 'count()'],
'chart':'',
'priority': 8,
},
{
'id':'chart0004',
'type':'chart',
'subType':'row',
'ingredients':[{'name':'who','tags':['#org']}],
'criteria':['who > 4', 'who < 11'],
'variables': ['who', 'count()'],
'chart':'',
'priority': 8,
},
{
'id':'chart0005',
'type':'chart',
'subType':'row',
'ingredients':[{'name':'where','tags':['#country-code','#region-code','#adm1-code','#adm2-code','#adm3-code','#adm4-code']}],
'criteria':['where > 4', 'where < 11'],
'variables': ['where', 'count()'],
'chart':'',
'priority': 8,
},
{
'id':'chart0006',
'type':'chart',
'subType':'pie',
'ingredients':[{'name':'where','tags':['#country-code','#region-code','#adm1-code','#adm2-code','#adm3-code','#adm4-code']}],
'criteria':['where > 1', 'where < 5'],
'variables': ['where', 'count()'],
'chart':'',
'priority': 8,
}
];